-- Supabase에서 모든 페이지의 content_tiptap를 토글 블록으로 변환하는 SQL

-- 1. 변환 함수 생성
CREATE OR REPLACE FUNCTION convert_node_to_toggle(node JSONB)
RETURNS JSONB AS $$
DECLARE
  node_type TEXT;
  content_array JSONB;
  new_content JSONB := '[]'::JSONB;
  item JSONB;
  converted_item JSONB;
BEGIN
  -- node가 null이면 그대로 반환
  IF node IS NULL THEN
    RETURN node;
  END IF;

  node_type := node->>'type';

  CASE node_type
    -- paragraph를 toggle로 변환
    WHEN 'paragraph' THEN
      RETURN jsonb_build_object(
        'type', 'toggle',
        'attrs', jsonb_build_object('isOpen', false, 'autoGenerated', false),
        'content', jsonb_build_array(node)
      );

    -- orderedList, bulletList의 각 항목을 toggle로 변환
    WHEN 'orderedList', 'bulletList' THEN
      content_array := node->'content';
      IF content_array IS NOT NULL THEN
        FOR item IN SELECT value FROM jsonb_array_elements(content_array)
        LOOP
          -- listItem을 toggle로 변환
          converted_item := jsonb_build_object(
            'type', 'toggle',
            'attrs', jsonb_build_object('isOpen', false, 'autoGenerated', false),
            'content', COALESCE(item->'content', '[]'::JSONB)
          );
          new_content := new_content || jsonb_build_array(converted_item);
        END LOOP;
      END IF;
      RETURN new_content;

    -- toggle은 내부 content를 재귀적으로 처리
    WHEN 'toggle' THEN
      content_array := node->'content';
      IF content_array IS NOT NULL THEN
        FOR item IN SELECT value FROM jsonb_array_elements(content_array)
        LOOP
          -- 첫 번째는 paragraph이므로 그대로, 나머지는 재귀 변환
          IF jsonb_array_length(new_content) = 0 THEN
            new_content := new_content || jsonb_build_array(item);
          ELSE
            new_content := new_content || convert_node_to_toggle(item);
          END IF;
        END LOOP;
      END IF;

      RETURN jsonb_build_object(
        'type', 'toggle',
        'attrs', COALESCE(node->'attrs', '{}'::JSONB) || jsonb_build_object('autoGenerated', false),
        'content', new_content
      );

    -- heading, codeBlock, table 등은 그대로 유지
    ELSE
      RETURN node;
  END CASE;
END;
$$ LANGUAGE plpgsql;

-- 2. 전체 문서를 변환하는 함수
CREATE OR REPLACE FUNCTION convert_document_to_toggles(doc JSONB)
RETURNS JSONB AS $$
DECLARE
  content_array JSONB;
  new_content JSONB := '[]'::JSONB;
  node JSONB;
  converted_nodes JSONB;
BEGIN
  -- 문서가 null이거나 content가 없으면 그대로 반환
  IF doc IS NULL OR doc->'content' IS NULL THEN
    RETURN doc;
  END IF;

  content_array := doc->'content';

  -- 각 노드를 변환
  FOR node IN SELECT value FROM jsonb_array_elements(content_array)
  LOOP
    converted_nodes := convert_node_to_toggle(node);

    -- 변환 결과가 배열이면 펼쳐서 추가, 아니면 단일 요소로 추가
    IF jsonb_typeof(converted_nodes) = 'array' THEN
      new_content := new_content || converted_nodes;
    ELSE
      new_content := new_content || jsonb_build_array(converted_nodes);
    END IF;
  END LOOP;

  -- 새로운 문서 반환
  RETURN jsonb_build_object(
    'type', COALESCE(doc->>'type', 'doc'),
    'content', new_content
  );
END;
$$ LANGUAGE plpgsql;

-- 3. 실제 데이터 변환 - 모든 페이지를 토글로 변환!
-- ⚠️ 주의: 백업을 먼저 하신 후 실행하세요!

UPDATE pages
SET content_tiptap = convert_document_to_toggles(content_tiptap)
WHERE content_tiptap IS NOT NULL;

-- 완료! 모든 페이지의 content_tiptap이 토글 블록으로 변환되었습니다.