// 목표 페이지 캡처 드로어 — "정리된 문서(content_tiptap) ↔ 난잡하게 떠오른 생각 캡처"를
// 분리해서 다루는 보조 영역. 목표 페이지(page_type='goal') 위에 슬라이드 인/아웃 오버레이로 뜬다.
//
// 설계(합의됨):
//  - (a) UX: 우측(또는 좌측) 슬라이드 드로어 오버레이. 본문 레이아웃(.tiptap-page-inner)을
//        건드리지 않도록 document.body 로 portal. 기본 우측·기본 닫힘.
//  - (b) 데이터: 캡처 내용은 pages.content_capture(JSONB) 보조 컬럼에 독립 저장
//        (content_tiptap 패턴 미러링). 본문 저장 경로(TipTapTestPage)는 전혀 건드리지 않는
//        자기완결 컴포넌트 — 자기 컬럼만 lazy 로드/디바운스 저장한다.
//  - (c) 좌/우 배치 + 열림 상태: localStorage(순수 UI 선호, 데일리 viewMode 컨벤션 동일).
//
// 캡처도 결국 텍스트/토글이므로 TipTapEditor 를 그대로 재사용한다.

import React, { useState, useEffect, useRef, useCallback } from 'react'
import { createPortal } from 'react-dom'
import TipTapEditor from '../TipTapEditor/TipTapEditor'
import { supabase } from '../../supabaseClient'
import './GoalCaptureDrawer.css'

// 빈 캡처 시작 문서 — TipTapTestPage 의 일반 페이지 빈 문서와 동일 형태.
const EMPTY_DOC = {
  type: 'doc',
  content: [{ type: 'toggle', attrs: { isOpen: true, autoGenerated: false }, content: [{ type: 'paragraph', content: [] }] }],
}
const SAVE_DEBOUNCE_MS = 500

const LS_OPEN = 'thinkmap.goalCaptureOpen'
const LS_SIDE = 'thinkmap.goalCaptureSide'
const LS_WIDTH = 'thinkmap.goalCaptureWidth'
const MIN_WIDTH = 280
const DEFAULT_WIDTH = 360

export default function GoalCaptureDrawer({ pageId, anchorRef }) {
  const [open, setOpen] = useState(() => {
    if (typeof window === 'undefined') return false
    return localStorage.getItem(LS_OPEN) === '1'
  })
  const [side, setSide] = useState(() => {
    if (typeof window === 'undefined') return 'right'
    return localStorage.getItem(LS_SIDE) === 'left' ? 'left' : 'right'
  })
  const [content, setContent] = useState(null)
  // 드로어 상단 y(뷰포트 기준) — 페이지 제목 div 아래(콘텐츠 시작 라인)에 맞춘다.
  const [topOffset, setTopOffset] = useState(null)
  // 패널 가로 너비(px) — 드래그로 조절, localStorage 저장. 최대는 페이지 영역 폭을 넘지 않음.
  const [width, setWidth] = useState(() => {
    if (typeof window === 'undefined') return DEFAULT_WIDTH
    const v = Number(localStorage.getItem(LS_WIDTH))
    return v >= MIN_WIDTH ? v : DEFAULT_WIDTH
  })

  const loadedPageRef = useRef(null)
  const saveTimerRef = useRef(null)
  const editorRef = useRef(null)
  const widthRef = useRef(width)
  useEffect(() => { widthRef.current = width }, [width])

  const setOpenPersist = useCallback((v) => {
    setOpen(v)
    try { localStorage.setItem(LS_OPEN, v ? '1' : '0') } catch {}
  }, [])

  const toggleSide = useCallback(() => {
    setSide((prev) => {
      const next = prev === 'right' ? 'left' : 'right'
      try { localStorage.setItem(LS_SIDE, next) } catch {}
      return next
    })
  }, [])

  // 드래그 리사이즈 — 안쪽 가장자리 그립을 잡고 좌우로 끌어 너비 조절.
  // 최대 너비는 페이지 콘텐츠 영역(.content-scrollable) 폭으로 클램프 → "페이지를 넘지 않음".
  const startResize = useCallback((e) => {
    e.preventDefault()
    const pageEl = anchorRef?.current
    const scrollEl = pageEl ? (pageEl.closest('.content-scrollable') || pageEl) : null
    const areaW = scrollEl ? scrollEl.getBoundingClientRect().width : window.innerWidth
    const maxW = Math.min(areaW, window.innerWidth)
    const prevUserSelect = document.body.style.userSelect
    document.body.style.userSelect = 'none'

    const onMove = (ev) => {
      const clientX = ev.clientX != null ? ev.clientX : ev.touches?.[0]?.clientX
      if (clientX == null) return
      // 우측 드로어: 오른쪽 끝(viewport 우단) 고정 → 너비 = innerWidth - clientX.
      // 좌측 드로어: 왼쪽 끝(0) 고정 → 너비 = clientX.
      const raw = side === 'right' ? (window.innerWidth - clientX) : clientX
      setWidth(Math.max(MIN_WIDTH, Math.min(maxW, raw)))
    }
    const onUp = () => {
      document.removeEventListener('pointermove', onMove)
      document.removeEventListener('pointerup', onUp)
      document.body.style.userSelect = prevUserSelect
      try { localStorage.setItem(LS_WIDTH, String(Math.round(widthRef.current))) } catch {}
    }
    document.addEventListener('pointermove', onMove)
    document.addEventListener('pointerup', onUp)
  }, [side, anchorRef])

  // 너비가 페이지 영역보다 커지지 않도록 리사이즈/사이드 변경 시 클램프
  useEffect(() => {
    const pageEl = anchorRef?.current
    if (!pageEl) return
    const scrollEl = pageEl.closest('.content-scrollable') || pageEl
    const clamp = () => {
      const maxW = Math.min(scrollEl.getBoundingClientRect().width, window.innerWidth)
      setWidth((w) => Math.min(Math.max(MIN_WIDTH, w), maxW))
    }
    clamp()
    window.addEventListener('resize', clamp)
    return () => window.removeEventListener('resize', clamp)
  }, [anchorRef, side])

  // pageId 가 바뀌면 콘텐츠 무효화 (다음 열림에서 새로 로드)
  useEffect(() => {
    setContent(null)
    loadedPageRef.current = null
  }, [pageId])

  // lazy 로드 — 처음 열릴 때(또는 열린 채 pageId 변경 시) content_capture 만 조회.
  // 닫혀있는 동안엔 아무 것도 fetch 하지 않아 기존 목표 페이지에 부담 없음.
  useEffect(() => {
    if (!open || !pageId) return
    if (loadedPageRef.current === pageId) return
    loadedPageRef.current = pageId
    let cancelled = false
    ;(async () => {
      const { data, error } = await supabase
        .from('pages')
        .select('content_capture')
        .eq('id', pageId)
        .single()
      if (cancelled) return
      if (error) {
        console.error('캡처 로드 실패:', error)
        setContent(EMPTY_DOC)
        return
      }
      setContent(data?.content_capture || EMPTY_DOC)
    })()
    return () => { cancelled = true }
  }, [open, pageId])

  // 디바운스 저장 — 자기 컬럼(content_capture)만 update. 본문(content_tiptap) 무관.
  const handleUpdate = useCallback((json) => {
    if (!pageId) return
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current)
    saveTimerRef.current = setTimeout(() => {
      supabase
        .from('pages')
        .update({ content_capture: json })
        .eq('id', pageId)
        .then(({ error }) => { if (error) console.error('캡처 저장 실패:', error) })
    }, SAVE_DEBOUNCE_MS)
  }, [pageId])

  // 언마운트 시 pending 저장 타이머 정리
  useEffect(() => () => { if (saveTimerRef.current) clearTimeout(saveTimerRef.current) }, [])

  // Esc 로 닫기 (열린 동안만) — 특히 모바일 풀폭 시 ✕ 외 회피 경로 제공
  useEffect(() => {
    if (!open) return
    const onKey = (e) => { if (e.key === 'Escape') setOpenPersist(false) }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open, setOpenPersist])

  // 드로어 top 을 "페이지 콘텐츠 시작 라인"에 맞춘다 — 제목(.tiptap-page-header) 바닥에 정렬.
  // 스크롤로 헤더가 위로 올라가면 페이지 스크롤 영역(.content-scrollable) 상단으로 클램프해
  // 앱 상단 바를 침범하지 않도록 한다. (닫힌 상태의 손잡이도 같은 라인에 두도록 항상 계산)
  useEffect(() => {
    const pageEl = anchorRef?.current
    if (!pageEl) return
    const scrollEl = pageEl.closest('.content-scrollable') || pageEl

    let rafId = 0
    const recalc = () => {
      rafId = 0
      const areaTop = scrollEl.getBoundingClientRect().top
      const headerEl = pageEl.querySelector('.tiptap-page-header')
      const desired = headerEl ? headerEl.getBoundingClientRect().bottom : areaTop
      setTopOffset(Math.max(areaTop, desired))
    }
    const schedule = () => { if (!rafId) rafId = requestAnimationFrame(recalc) }

    recalc()
    window.addEventListener('resize', schedule)
    // 내부 스크롤 컨테이너에서 일어나는 스크롤을 잡기 위해 capture
    window.addEventListener('scroll', schedule, true)
    const ro = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(schedule) : null
    ro?.observe(scrollEl)

    return () => {
      if (rafId) cancelAnimationFrame(rafId)
      window.removeEventListener('resize', schedule)
      window.removeEventListener('scroll', schedule, true)
      ro?.disconnect()
    }
  }, [anchorRef, pageId])

  if (!pageId) return null

  return createPortal(
    <div className={`goal-capture goal-capture--${side}${open ? ' goal-capture--open' : ''}`}>
      {/* 손잡이 — 닫혀있을 때만 보임. 클릭 시 열림 */}
      {!open && (
        <button
          type="button"
          className="goal-capture-handle"
          onClick={() => setOpenPersist(true)}
          title="생각 캡처 열기"
          style={topOffset != null ? { top: topOffset, transform: 'none' } : undefined}
        >
          <span>캡처</span>
        </button>
      )}

      {/* 슬라이드 패널 */}
      <aside
        className="goal-capture-panel"
        aria-hidden={!open}
        style={{ width, ...(topOffset != null ? { top: topOffset } : {}) }}
      >
        {/* 안쪽 가장자리 드래그 그립 — 너비 조절 */}
        <div
          className="goal-capture-resizer"
          onPointerDown={startResize}
          role="separator"
          aria-orientation="vertical"
          aria-label="캡처 너비 조절"
          title="드래그해서 너비 조절"
        />
        <div className="goal-capture-header">
          <span className="goal-capture-title">생각 캡처</span>
          <div className="goal-capture-header-actions">
            <button
              type="button"
              className="goal-capture-icon-btn"
              onClick={toggleSide}
              title={side === 'right' ? '왼쪽으로 이동' : '오른쪽으로 이동'}
              aria-label="좌/우 위치 변경"
            >
              <span className="goal-capture-glyph">⇄</span>
            </button>
            <button
              type="button"
              className="goal-capture-icon-btn"
              onClick={() => setOpenPersist(false)}
              title="닫기"
              aria-label="캡처 닫기"
            >
              <span className="goal-capture-glyph">✕</span>
            </button>
          </div>
        </div>
        <div className="goal-capture-body">
          {content ? (
            <TipTapEditor
              content={content}
              onUpdate={handleUpdate}
              placeholder="떠오른 생각을 빠르게 적어두세요..."
              editorRef={editorRef}
              isMaster={false}
              isDailyPage={false}
            />
          ) : (
            <div className="goal-capture-loading">로딩 중...</div>
          )}
        </div>
      </aside>
    </div>,
    document.body
  )
}
