/**
 * 페이지 양식 (템플릿) 정의
 * 새 페이지 생성 시 선택 가능한 양식 목록
 */

/** 오늘 날짜를 YYYY-MM-DD 형식으로 반환 */
const today = () => new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' }).replace(/\. /g, '-').replace('.', '')

/** 텍스트 노드 생성 헬퍼 */
const text = (t, marks) => marks ? { type: 'text', text: t, marks } : { type: 'text', text: t }
const bold = (t) => text(t, [{ type: 'bold' }])

/** 빈 paragraph */
const emptyPara = () => ({ type: 'paragraph', content: [] })

/** 텍스트가 있는 paragraph */
const para = (...nodes) => ({ type: 'paragraph', content: nodes })

/** 헤딩 */
const heading = (level, ...nodes) => ({ type: 'heading', attrs: { level }, content: nodes })

/** 토글 블록 (열림/닫힘) */
const toggle = (isOpen, ...content) => ({
  type: 'toggle',
  attrs: { isOpen, autoGenerated: false },
  content,
})

/** 체크박스(taskList) 스타일의 paragraph — TipTap 기본 paragraph로 체크박스 표현 */
const checkItem = (label) => para(text(`☐ ${label}`))

// ─── 양식 목록 ───

export const PAGE_TEMPLATES = [
  {
    id: 'blank',
    name: '빈 페이지',
    icon: '📄',
    description: '빈 페이지에서 자유롭게 시작',
    getContent: () => null, // content_tiptap = null → 에디터 기본 빈 문서
  },
  {
    id: 'work-journal',
    name: '업무일지',
    icon: '📋',
    description: '일일 업무 기록 양식',
    getDefaultName: () => `업무일지 ${today()}`,
    getContent: () => ({
      type: 'doc',
      content: [
        // 날짜 헤딩
        toggle(true,
          heading(2, bold(`📋 업무일지 — ${today()}`)),
        ),
        // 오늘의 목표
        toggle(true,
          para(bold('🎯 오늘의 목표')),
          checkItem(''),
        ),
        // 업무 내용
        toggle(true,
          para(bold('📝 업무 내용')),
          toggle(true,
            para(text('업무 1')),
            para(text('내용을 입력하세요.')),
          ),
        ),
        // 회의 / 미팅
        toggle(true,
          para(bold('🤝 회의 / 미팅')),
          para(text('회의 내용을 기록하세요.')),
        ),
        // 이슈 / 문제점
        toggle(true,
          para(bold('⚠️ 이슈 / 문제점')),
          para(text('')),
        ),
        // 내일 할 일
        toggle(true,
          para(bold('📌 내일 할 일')),
          checkItem(''),
        ),
        // 메모
        toggle(false,
          para(bold('💡 메모')),
          para(text('')),
        ),
      ],
    }),
  },
]
