/**
 * TipTap 토글 노드 생성 팩토리
 * 업무일지 템플릿, QuickTodo 등에서 공통 사용
 */

import { genBlockId } from './blockId'

export function genSectionId() {
  return 'sec_' + Math.random().toString(36).slice(2, 10)
}

// 기본 toggle attrs
const BASE_ATTRS = {
  isOpen: true,
  isTodo: false,
  pageId: null,
  blockType: 'paragraph',
  todoStatus: null,
  todoChecked: false,
  autoGenerated: false,
  backgroundColor: null,
  isFixedSection: false,
  isStarred: false,
  blockId: null,
  originBlockId: null,
}

function toggleNode(attrs, content) {
  return { type: 'toggle', attrs: { ...BASE_ATTRS, ...attrs }, content }
}

function boldParagraph(text) {
  return { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text }] }
}

function textParagraph(text) {
  return { type: 'paragraph', content: [{ type: 'text', text }] }
}

/** 빈 토글 (todo 또는 일반) */
export function emptyToggle(isTodo = false) {
  return toggleNode({ isTodo }, [{ type: 'paragraph' }])
}

/** 섹션 토글 (h2/h3, 고정/자유) */
export function sectionToggle(title, blockType, children, { isFixed = false, visibility = 'all', sectionId = null } = {}) {
  return toggleNode(
    { blockType, isFixedSection: isFixed, visibility, sectionId: sectionId || genSectionId() },
    [boldParagraph(title), ...children]
  )
}

/** Pinned 섹션 토글 */
export function pinnedSectionToggle(title, blockType, children, { visibility = 'all', sectionId = null } = {}) {
  return toggleNode(
    { blockType, isPinned: true, visibility, sectionId: sectionId || genSectionId() },
    [boldParagraph(title), ...children]
  )
}

/** 이월 투두 토글 */
export function carryOverToggle(text, fromDate) {
  return toggleNode(
    { isTodo: true, isCarryOver: true, carryOverFrom: fromDate },
    [textParagraph(text)]
  )
}

/** 일반 투두 토글 (QuickTodo 등에서 사용) */
export function todoToggle(text) {
  return toggleNode(
    { isTodo: true, isCarryOver: false, carryOverFrom: null, visibility: 'all', isPinned: false,
      blockId: genBlockId() },
    [textParagraph(text)]
  )
}
