/**
 * 업무일지(daily) 페이지 초기 콘텐츠 템플릿
 * CalendarView에서 "+" 클릭 시 이 구조로 daily 페이지가 생성됨
 */

function sectionToggle(title, blockType, children, isFixed = false) {
  return {
    type: 'toggle',
    attrs: {
      isOpen: true,
      isTodo: false,
      pageId: null,
      blockType,
      todoStatus: null,
      todoChecked: false,
      autoGenerated: false,
      backgroundColor: null,
      isFixedSection: isFixed,
    },
    content: [
      {
        type: 'paragraph',
        content: [{ type: 'text', marks: [{ type: 'bold' }], text: title }],
      },
      ...children,
    ],
  }
}

function emptyToggle(isTodo = false) {
  return {
    type: 'toggle',
    attrs: {
      isOpen: true,
      isTodo,
      pageId: null,
      blockType: 'paragraph',
      todoStatus: null,
      todoChecked: false,
      autoGenerated: false,
      backgroundColor: null,
      isFixedSection: false,
    },
    content: [{ type: 'paragraph' }],
  }
}

export function createWorklogTemplate() {
  return {
    type: 'doc',
    content: [
      // 섹션 1: 할 일 (고정)
      sectionToggle('할 일', 'h2', [
        emptyToggle(true),
      ], true),

      // 섹션 2: 전달사항 (고정)
      sectionToggle('전달사항', 'h2', [
        emptyToggle(false),
      ], true),

      // 섹션 3: 마무리 기록 (고정)
      sectionToggle('마무리 기록', 'h2', [
        sectionToggle('당일 이슈', 'h3', [
          emptyToggle(false),
        ], true),
      ], true),
    ],
  }
}
