/**
 * 업무일지(daily) 페이지 초기 콘텐츠 템플릿
 * CalendarView에서 "+" 클릭 시 이 구조로 daily 페이지가 생성됨
 */

function sectionToggle(title, blockType, children, isFixed = false, visibility = 'all') {
  return {
    type: 'toggle',
    attrs: {
      isOpen: true,
      isTodo: false,
      pageId: null,
      blockType,
      todoStatus: null,
      todoChecked: false,
      autoGenerated: false,
      backgroundColor: null,
      isFixedSection: isFixed,
      visibility,
    },
    content: [
      {
        type: 'paragraph',
        content: [{ type: 'text', marks: [{ type: 'bold' }], text: title }],
      },
      ...children,
    ],
  }
}

function emptyToggle(isTodo = false) {
  return {
    type: 'toggle',
    attrs: {
      isOpen: true,
      isTodo,
      pageId: null,
      blockType: 'paragraph',
      todoStatus: null,
      todoChecked: false,
      autoGenerated: false,
      backgroundColor: null,
      isFixedSection: false,
    },
    content: [{ type: 'paragraph' }],
  }
}

function carryOverToggle(text, fromDate) {
  return {
    type: 'toggle',
    attrs: {
      isOpen: true,
      isTodo: true,
      pageId: null,
      blockType: 'paragraph',
      todoStatus: null,
      todoChecked: false,
      autoGenerated: false,
      backgroundColor: null,
      isFixedSection: false,
      isCarryOver: true,
      carryOverFrom: fromDate,
    },
    content: [
      {
        type: 'paragraph',
        content: [{ type: 'text', text }],
      },
    ],
  }
}

/**
 * pinnedSections: 이전 daily 페이지에서 추출한 pinned 섹션 제목 배열
 * carryOverTodos: 이월할 미완료 todo 배열 [{ text, fromDate }]
 */
export function createWorklogTemplate(pinnedSections = [], carryOverTodos = []) {
  const pinnedNodes = pinnedSections.map(s => {
    const title = typeof s === 'string' ? s : s.title
    const visibility = typeof s === 'string' ? 'all' : (s.visibility || 'all')
    return pinnedSectionToggle(title, 'h2', [emptyToggle(false)], visibility)
  })

  const carryOverNodes = carryOverTodos.map(t => carryOverToggle(t.text, t.fromDate))

  return {
    type: 'doc',
    content: [
      // 섹션 1: 할 일 (고정) — 이월 항목이 빈 todo 앞에 삽입
      sectionToggle('할 일', 'h2', [
        ...carryOverNodes,
        emptyToggle(true),
      ], true),

      // 섹션 2: 전달사항 (고정)
      sectionToggle('전달사항', 'h2', [
        emptyToggle(false),
      ], true),

      // pinned 자유 섹션 (마무리 기록 앞)
      ...pinnedNodes,

      // 섹션 3: 마무리 기록 (고정)
      sectionToggle('마무리 기록', 'h2', [
        sectionToggle('당일 이슈', 'h3', [
          emptyToggle(false),
        ], true),
      ], true),
    ],
  }
}

function pinnedSectionToggle(title, blockType, children, visibility = 'all') {
  return {
    type: 'toggle',
    attrs: {
      isOpen: true,
      isTodo: false,
      pageId: null,
      blockType,
      todoStatus: null,
      todoChecked: false,
      autoGenerated: false,
      backgroundColor: null,
      isFixedSection: false,
      isPinned: true,
      visibility,
    },
    content: [
      {
        type: 'paragraph',
        content: [{ type: 'text', marks: [{ type: 'bold' }], text: title }],
      },
      ...children,
    ],
  }
}
