import { Node, mergeAttributes, InputRule } from '@tiptap/core'
import { NodeSelection, TextSelection, Selection, Plugin, PluginKey } from '@tiptap/pm/state'
import { Decoration, DecorationSet } from '@tiptap/pm/view'

// --- CheckboxSelection: 체크박스가 '선택된' 상태를 나타내는 커스텀 Selection ---

class CheckboxBookmark {
  constructor(togglePos) { this.togglePos = togglePos }
  map(mapping) { return new CheckboxBookmark(mapping.map(this.togglePos)) }
  resolve(doc) {
    const node = doc.nodeAt(this.togglePos)
    if (node && node.type.name === 'toggle' && node.attrs.isTodo) {
      return new CheckboxSelection(doc.resolve(this.togglePos + 2), this.togglePos)
    }
    return TextSelection.near(doc.resolve(this.togglePos))
  }
}

class CheckboxSelection extends Selection {
  constructor($pos, togglePos) {
    super($pos, $pos)
    this.togglePos = togglePos
  }

  get node() { return this.$anchor.doc.nodeAt(this.togglePos) }

  map(doc, mapping) {
    const mappedPos = mapping.map(this.togglePos)
    const node = doc.nodeAt(mappedPos)
    if (node && node.type.name === 'toggle' && node.attrs.isTodo) {
      return new CheckboxSelection(doc.resolve(mappedPos + 2), mappedPos)
    }
    return TextSelection.near(doc.resolve(mapping.map(this.from)))
  }

  eq(other) {
    return other instanceof CheckboxSelection && other.togglePos === this.togglePos
  }

  toJSON() { return { type: 'checkbox', togglePos: this.togglePos } }
  static fromJSON(doc, json) {
    return new CheckboxSelection(doc.resolve(json.togglePos + 2), json.togglePos)
  }

  getBookmark() { return new CheckboxBookmark(this.togglePos) }
}

Selection.jsonID('checkbox', CheckboxSelection)

// --- 헬퍼 함수 ---

/** 노드에 하위 토글이 있는지 확인 (첫 번째 자식은 paragraph이므로 인덱스 1부터 검사) */
function hasChildToggles(node) {
  for (let i = 1; i < node.childCount; i++) {
    if (node.child(i).type.name === 'toggle') return true
  }
  return false
}

/** $from 위치에서 가장 가까운 토글의 depth 반환, 없으면 -1 */
function findToggleDepth($from) {
  for (let d = $from.depth; d > 0; d--) {
    if ($from.node(d).type.name === 'toggle') return d
  }
  return -1
}

/** 화면에 보이는 블록 위치를 순서대로 수집 (닫힌 토글의 하위는 제외) */
function collectVisiblePositions(doc) {
  const positions = []
  function visit(node, pos) {
    positions.push(pos)
    if (node.type.name === 'toggle' && node.attrs.isOpen && node.childCount > 1) {
      let childPos = pos + 1 + node.child(0).nodeSize
      for (let i = 1; i < node.childCount; i++) {
        visit(node.child(i), childPos)
        childPos += node.child(i).nodeSize
      }
    }
  }
  let pos = 0
  for (let i = 0; i < doc.childCount; i++) {
    visit(doc.child(i), pos)
    pos += doc.child(i).nodeSize
  }
  return positions
}

/** 빈 토글 JSON 객체 반환 */
function emptyToggleJSON(isOpen = true, autoGenerated = false, extraAttrs = {}) {
  return {
    type: 'toggle',
    attrs: { isOpen, autoGenerated, ...extraAttrs },
    content: [{ type: 'paragraph', content: [] }]
  }
}

/** listItem JSON → toggle JSON 변환 (재귀: 중첩 리스트 → 중첩 토글) */
function convertListItemToToggleJSON(listItem) {
  const children = []
  ;(listItem.content || []).forEach(child => {
    if (child.type === 'paragraph') {
      children.push(child)
    } else if (child.type === 'orderedList' || child.type === 'bulletList') {
      ;(child.content || []).forEach(subItem => children.push(convertListItemToToggleJSON(subItem)))
    } else {
      children.push(child)
    }
  })
  if (children.length === 0 || children[0]?.type !== 'paragraph') {
    children.unshift({ type: 'paragraph', content: [] })
  }
  const hasChildToggleNodes = children.slice(1).some(c => c.type === 'toggle')
  return { type: 'toggle', attrs: { isOpen: hasChildToggleNodes }, content: children }
}

/** 문서 노드 JSON → toggle JSON 배열 변환 (재귀: toggle 내부도 처리) */
function convertNodeToTogglesJSON(node) {
  switch (node.type) {
    case 'paragraph':
      return [{ type: 'toggle', attrs: { isOpen: false }, content: [node] }]
    case 'orderedList':
    case 'bulletList':
      return (node.content || []).map(convertListItemToToggleJSON)
    case 'toggle': {
      const newChildren = []
      ;(node.content || []).forEach(child => newChildren.push(...convertNodeToTogglesJSON(child)))
      const hasChildToggleNodes = newChildren.slice(1).some(c => c.type === 'toggle')
      return [{ ...node, attrs: { ...node.attrs, isOpen: hasChildToggleNodes }, content: newChildren }]
    }
    default:
      return [node] // heading, codeBlock, table 등 → 그대로 유지
  }
}

/**
 * Toggle Extension for TipTap
 * Notion-style collapsible blocks with children
 */
export const Toggle = Node.create({
  name: 'toggle',

  priority: 200, // 키보드 핸들러가 다른 익스텐션보다 먼저 실행되도록 (줄바꿈 방지)

  group: 'block',

  content: '(paragraph | toggle)+',

  defining: true,

  addAttributes() {
    return {
      isOpen: {
        default: true,
        parseHTML: element => element.getAttribute('data-is-open') === 'true',
        renderHTML: attributes => {
          return {
            'data-is-open': attributes.isOpen,
          }
        },
      },
      autoGenerated: {
        default: false,
        parseHTML: element => element.getAttribute('data-auto-generated') === 'true',
        renderHTML: attributes => {
          return attributes.autoGenerated ? {
            'data-auto-generated': 'true',
          } : {}
        },
      },
      isTodo: {
        default: false,
        parseHTML: element => element.getAttribute('data-is-todo') === 'true',
        renderHTML: attributes => attributes.isTodo ? { 'data-is-todo': 'true' } : {},
      },
      todoChecked: {
        default: false,
        parseHTML: element => element.getAttribute('data-todo-checked') === 'true',
        renderHTML: attributes => attributes.todoChecked ? { 'data-todo-checked': 'true' } : {},
      },
    }
  },

  parseHTML() {
    return [
      {
        tag: 'div[data-type="toggle"]',
      },
    ]
  },

  renderHTML({ node, HTMLAttributes }) {
    return [
      'div',
      mergeAttributes(HTMLAttributes, {
        'data-type': 'toggle',
        'data-is-open': node.attrs.isOpen,
        class: 'toggle-block',
      }),
      [
        'div',
        { class: 'toggle-header' },
        [
          'button',
          {
            class: 'toggle-button',
            contenteditable: 'false',
            'data-toggle-button': 'true',
          },
          node.attrs.isOpen ? '▼' : '▶',
        ],
        ['div', { class: 'toggle-content-wrapper' }, 0],
      ],
      [
        'div',
        {
          class: node.attrs.isOpen ? 'toggle-children open' : 'toggle-children closed',
        },
        // children will be rendered here by TipTap
      ],
    ]
  },

  addNodeView() {
    return ({ node, editor, getPos, decorations }) => {
      const dom = document.createElement('div')
      dom.classList.add('toggle-block')
      dom.setAttribute('data-is-open', node.attrs.isOpen)

      // 초기 decoration 적용
      const hasFocusClass = (decos) =>
        decos?.some(d => d.type?.attrs?.class?.includes('toggle-block-focused'))
      const hasCheckboxFocusClass = (decos) =>
        decos?.some(d => d.type?.attrs?.class?.includes('toggle-checkbox-focused'))
      if (hasFocusClass(decorations)) dom.classList.add('toggle-block-focused')
      if (hasCheckboxFocusClass(decorations)) dom.classList.add('toggle-checkbox-focused')

      // 드래그 핸들 (블록 내부에 배치)
      const dragHandle = document.createElement('div')
      dragHandle.classList.add('toggle-drag-handle')
      dragHandle.contentEditable = 'false'
      dragHandle.draggable = true

      // 드래그 시작 이벤트
      dragHandle.addEventListener('dragstart', (e) => {
        if (typeof getPos !== 'function') return

        const pos = getPos()
        const nodeAtPos = editor.state.doc.nodeAt(pos)
        if (!nodeAtPos) return

        // 노드 선택
        const selection = NodeSelection.create(editor.state.doc, pos)
        editor.view.dispatch(editor.state.tr.setSelection(selection))

        // 드래그 데이터 설정
        const slice = editor.state.selection.content()
        e.dataTransfer.effectAllowed = 'move'
        e.dataTransfer.setDragImage(dom, 0, 0)

        editor.view.dragging = { slice, move: true }
      })

      // 드래그 핸들 클릭 시 블록 선택 + 컨텍스트 메뉴
      dragHandle.addEventListener('click', (e) => {
        e.preventDefault()
        e.stopPropagation()

        if (typeof getPos !== 'function') return

        const pos = getPos()
        const selection = NodeSelection.create(editor.state.doc, pos)
        editor.view.dispatch(editor.state.tr.setSelection(selection))

        // 커스텀 이벤트로 컨텍스트 메뉴 표시 요청
        const rect = dragHandle.getBoundingClientRect()
        dom.dispatchEvent(new CustomEvent('toggle-context-menu', {
          bubbles: true,
          detail: { pos, top: rect.bottom + 5, left: rect.left }
        }))
      })

      // Toggle button
      const button = document.createElement('button')
      button.classList.add('toggle-button')
      button.contentEditable = 'false'
      button.textContent = hasChildToggles(node)
        ? (node.attrs.isOpen ? '▼' : '▶')
        : (node.attrs.isOpen ? '▽' : '▷')

      // Content area (contentDOM) - 버튼 옆에 배치
      const contentWrapper = document.createElement('div')
      contentWrapper.classList.add('toggle-content')
      contentWrapper.classList.add(node.attrs.isOpen ? 'open' : 'closed')

      button.addEventListener('mousedown', (e) => {
        e.preventDefault()
        e.stopPropagation()

        if (typeof getPos !== 'function') return

        const pos = getPos()
        const currentNode = editor.state.doc.nodeAt(pos)
        if (!currentNode) return

        const newIsOpen = !currentNode.attrs.isOpen
        const { tr } = editor.state
        tr.setNodeMarkup(pos, null, { ...currentNode.attrs, isOpen: newIsOpen })
        // 버튼 클릭임을 표시 → 플러그인이 자동 열기를 건너뜀
        tr.setMeta('toggleButtonClick', true)

        if (newIsOpen) {
          // 열 때, 하위 토글이 없으면 빈 하위 토글 자동 생성
          if (!hasChildToggles(currentNode)) {
            const insertPos = pos + currentNode.nodeSize - 1
            tr.insert(insertPos, editor.state.schema.nodeFromJSON(emptyToggleJSON(true, true)))
          }
        } else {
          // 닫을 때, 자동 생성된 빈 토글들을 삭제
          if (hasChildToggles(currentNode)) {
            const updatedNode = tr.doc.nodeAt(pos)
            if (updatedNode) {
              let deleteOffset = 0
              // 첫 번째 자식은 paragraph이므로 인덱스 1부터 검사
              for (let i = 1; i < updatedNode.childCount; i++) {
                const child = updatedNode.child(i)
                if (child.type.name === 'toggle' &&
                    child.attrs.autoGenerated &&
                    child.childCount === 1 &&
                    child.firstChild?.type.name === 'paragraph' &&
                    child.firstChild?.content.size === 0) {
                  // 자동 생성된 빈 토글 삭제
                  const childPos = pos + 1 + updatedNode.child(0).nodeSize + deleteOffset
                  tr.delete(childPos, childPos + child.nodeSize)
                  deleteOffset -= child.nodeSize
                } else {
                  deleteOffset += child.nodeSize
                }
              }
            }
          }
        }

        editor.view.dispatch(tr)
      })

      // Todo checkbox
      const checkbox = document.createElement('div')
      checkbox.classList.add('toggle-todo-checkbox')
      checkbox.contentEditable = 'false'

      // SVG checkmark
      const svgNS = 'http://www.w3.org/2000/svg'
      const svg = document.createElementNS(svgNS, 'svg')
      svg.setAttribute('viewBox', '0 0 12 12')
      svg.classList.add('checkbox-icon')
      const path = document.createElementNS(svgNS, 'path')
      path.setAttribute('d', 'M2.5 6.5L5 9L9.5 3.5')
      svg.appendChild(path)
      checkbox.appendChild(svg)

      // Particle elements
      const particles = document.createElement('div')
      particles.classList.add('checkbox-particles')
      for (let i = 0; i < 6; i++) {
        particles.appendChild(document.createElement('span'))
      }
      checkbox.appendChild(particles)

      if (!node.attrs.isTodo) checkbox.style.display = 'none'
      if (node.attrs.todoChecked) {
        checkbox.classList.add('checked')
        dom.classList.add('toggle-todo-checked')
      }

      checkbox.addEventListener('mousedown', (e) => {
        e.preventDefault()
        e.stopPropagation()
        if (typeof getPos !== 'function') return
        const pos = getPos()
        const currentNode = editor.state.doc.nodeAt(pos)
        if (!currentNode) return
        const willCheck = !currentNode.attrs.todoChecked
        // Re-trigger animations by removing and re-adding checked class
        if (willCheck) {
          checkbox.classList.remove('checked')
          void checkbox.offsetWidth // force reflow
        }
        const { tr } = editor.state
        tr.setNodeMarkup(pos, null, { ...currentNode.attrs, todoChecked: willCheck })
        editor.view.dispatch(tr)
      })

      dom.appendChild(dragHandle)
      dom.appendChild(button)
      dom.appendChild(checkbox)
      dom.appendChild(contentWrapper)

      return {
        dom,
        contentDOM: contentWrapper,
        update: (updatedNode, outerDecorations) => {
          if (updatedNode.type.name !== 'toggle') return false

          button.textContent = hasChildToggles(updatedNode)
            ? (updatedNode.attrs.isOpen ? '▼' : '▶')
            : (updatedNode.attrs.isOpen ? '▽' : '▷')
          contentWrapper.className = updatedNode.attrs.isOpen
            ? 'toggle-content open'
            : 'toggle-content closed'
          dom.setAttribute('data-is-open', updatedNode.attrs.isOpen)

          // Decoration 반영 (Plugin이 전달한 포커스 상태)
          dom.classList.toggle('toggle-block-focused', hasFocusClass(outerDecorations))
          dom.classList.toggle('toggle-checkbox-focused', hasCheckboxFocusClass(outerDecorations))

          // Todo checkbox update
          if (updatedNode.attrs.isTodo) {
            checkbox.style.display = ''
            checkbox.classList.toggle('checked', updatedNode.attrs.todoChecked)
            dom.classList.toggle('toggle-todo-checked', updatedNode.attrs.todoChecked)
          } else {
            checkbox.style.display = 'none'
            checkbox.classList.remove('checked')
            dom.classList.remove('toggle-todo-checked')
          }

          return true
        },
      }
    }
  },

  addProseMirrorPlugins() {
    return [
      // CheckboxSelection: decoration + 스페이스바 토글
      new Plugin({
        props: {
          decorations(state) {
            if (!(state.selection instanceof CheckboxSelection)) return DecorationSet.empty
            const { togglePos } = state.selection
            const node = state.doc.nodeAt(togglePos)
            if (!node) return DecorationSet.empty
            return DecorationSet.create(state.doc, [
              Decoration.node(togglePos, togglePos + node.nodeSize, {
                class: 'toggle-checkbox-focused',
              }),
            ])
          },
          handleKeyDown(view, event) {
            if (!(view.state.selection instanceof CheckboxSelection)) return false
            if (event.key !== ' ') return false

            event.preventDefault()
            const { togglePos } = view.state.selection
            const node = view.state.doc.nodeAt(togglePos)
            if (!node) return false

            const { tr } = view.state
            tr.setNodeMarkup(togglePos, null, { ...node.attrs, todoChecked: !node.attrs.todoChecked })
            tr.setSelection(new CheckboxSelection(tr.doc.resolve(togglePos + 2), togglePos))
            view.dispatch(tr)
            return true
          }
        }
      }),
      new Plugin({
        appendTransaction(transactions, _oldState, newState) {
          // 선택 변경이 있는 트랜잭션에서만 실행
          if (!transactions.some(tr => tr.selectionSet || tr.docChanged)) return null

          // 버튼 클릭으로 직접 토글한 경우 자동 열기 건너뜀
          if (transactions.some(tr => tr.getMeta('toggleButtonClick'))) return null

          const { $from } = newState.selection

          for (let d = $from.depth; d > 0; d--) {
            const node = $from.node(d)
            if (node.type.name === 'toggle' && !node.attrs.isOpen) {
              // 커서가 첫 번째 자식(paragraph) 안에 있으면 자동 열기 안함
              // paragraph는 닫힌 상태에서도 CSS로 보이므로 커서 이동은 정상
              const toggleStart = $from.before(d)
              const paragraphEnd = toggleStart + 1 + node.child(0).nodeSize
              if ($from.pos < paragraphEnd) break

              if (hasChildToggles(node)) {
                const tr = newState.tr
                tr.setNodeMarkup(toggleStart, null, { ...node.attrs, isOpen: true })
                return tr
              }
              break
            }
          }

          return null
        },
      }),
      // 스페이스바: 토글 화살표(NodeSelection) → 열기/닫기
      new Plugin({
        props: {
          handleKeyDown(view, event) {
            if (event.key !== ' ') return false
            const { state } = view
            const { selection } = state

            if (!(selection instanceof NodeSelection)) return false
            if (selection.node.type.name !== 'toggle') return false

            const pos = selection.from
            const node = selection.node
            const willOpen = !node.attrs.isOpen
            const { tr } = state
            tr.setNodeMarkup(pos, null, { ...node.attrs, isOpen: willOpen })

            // 열 때 하위 토글이 없으면 빈 하위 토글 자동 생성
            if (willOpen && !hasChildToggles(node)) {
              const insertPos = pos + node.nodeSize - 1
              tr.insert(insertPos, state.schema.nodeFromJSON(emptyToggleJSON(true, true)))
            }

            tr.setMeta('toggleButtonClick', true)
            view.dispatch(tr)

            // DOM 업데이트 후 선택 복원
            requestAnimationFrame(() => {
              const tr2 = view.state.tr
              tr2.setSelection(NodeSelection.create(view.state.doc, pos))
              tr2.setMeta('toggleButtonClick', true)
              view.dispatch(tr2)
            })
            return true
          },
        },
      }),
      // 커서가 위치한 가장 가까운(가장 안쪽) 토글 블록에 포커스 decoration
      new Plugin({
        key: new PluginKey('toggleFocusHighlight'),
        props: {
          decorations(state) {
            const { selection } = state
            let pos = -1

            // NodeSelection: 선택된 토글 자체
            if (selection instanceof NodeSelection && selection.node.type.name === 'toggle') {
              pos = selection.from
            }
            // CheckboxSelection: 해당 토글
            else if (selection instanceof CheckboxSelection) {
              pos = selection.togglePos
            }
            // TextSelection: 커서가 위치한 가장 안쪽 토글
            else {
              const { $from } = selection
              const depth = findToggleDepth($from)
              if (depth !== -1) pos = $from.before(depth)
            }

            if (pos === -1) return DecorationSet.empty
            const node = state.doc.nodeAt(pos)
            if (!node) return DecorationSet.empty

            return DecorationSet.create(state.doc, [
              Decoration.node(pos, pos + node.nodeSize, {
                class: 'toggle-block-focused',
              }),
            ])
          },
        },
      }),
    ]
  },

  addCommands() {
    return {
      setToggle: () => ({ editor, chain }) => {
        const { state } = editor
        const { selection } = state

        // 에디터가 비어있는지 확인 (doc에 빈 paragraph만 있는 경우)
        const isEmptyDoc = state.doc.content.size <= 2 ||
          (state.doc.childCount === 1 &&
           state.doc.firstChild?.type.name === 'paragraph' &&
           state.doc.firstChild?.content.size === 0)

        if (isEmptyDoc) {
          // 빈 에디터: 전체를 토글로 대체
          return chain()
            .clearContent()
            .insertContent(emptyToggleJSON())
            .focus()
            .run()
        }

        // 현재 블록 끝으로 이동 후 새 줄에 토글 삽입
        return chain()
          .insertContentAt(selection.to, emptyToggleJSON())
          .focus()
          .run()
      },
      toggleTodo: () => ({ editor }) => {
        const { state } = editor
        const { selection } = state
        let togglePos, toggleNode

        if (selection instanceof NodeSelection && selection.node.type.name === 'toggle') {
          togglePos = selection.from
          toggleNode = selection.node
        } else {
          const toggleDepth = findToggleDepth(state.selection.$from)
          if (toggleDepth === -1) return false
          togglePos = state.selection.$from.before(toggleDepth)
          toggleNode = state.doc.nodeAt(togglePos)
        }

        if (!toggleNode) return false

        const { tr } = state
        const newIsTodo = !toggleNode.attrs.isTodo
        tr.setNodeMarkup(togglePos, null, {
          ...toggleNode.attrs,
          isTodo: newIsTodo,
          todoChecked: newIsTodo ? toggleNode.attrs.todoChecked : false,
        })
        editor.view.dispatch(tr)
        return true
      },
      toggleToggle: () => ({ commands, editor }) => {
        const { state } = editor
        const { $from } = state.selection
        const node = $from.parent

        if (node.type.name === 'toggle') {
          return commands.updateAttributes('toggle', {
            isOpen: !node.attrs.isOpen,
          })
        }

        return false
      },

      // paragraph, orderedList, bulletList → toggle 변환 (heading/codeBlock 등은 유지)
      convertAllToToggle: () => ({ editor }) => {
        const json = editor.getJSON()
        if (!json?.content) return false

        const newContent = []
        json.content.forEach(node => newContent.push(...convertNodeToTogglesJSON(node)))

        editor.commands.setContent({ ...json, content: newContent })
        return true
      },
    }
  },

  addKeyboardShortcuts() {
    // 커서가 paragraph 끝에 있을 때: 열린 토글이면 하위 첫 위치에, 아니면 형제 위치에 새 토글 삽입
    function handleEnterAtEnd(editor, $from, toggleDepth, toggleNode, togglePos, afterTogglePos) {
      const newAttrs = toggleNode.attrs.isTodo ? { isTodo: true, todoChecked: false } : {}
      if (toggleNode.attrs.isOpen && hasChildToggles(toggleNode)) {
        const paragraphNode = $from.node(toggleDepth + 1)
        const firstChildPos = togglePos + 1 + paragraphNode.nodeSize
        editor.chain()
          .insertContentAt(firstChildPos, emptyToggleJSON(true, false, newAttrs))
          .focus(firstChildPos + 2)
          .run()
        return true
      }
      editor.chain()
        .insertContentAt(afterTogglePos, emptyToggleJSON(true, false, newAttrs))
        .focus(afterTogglePos + 2)
        .run()
      return true
    }

    // 커서가 paragraph 중간에 있을 때: 이후 내용을 잘라서 새 토글로 분리
    function handleEnterAtMiddle(editor, $from, toggleDepth, afterTogglePos, paragraphEnd, toggleNode) {
      const { state } = editor
      const paragraphNode = $from.node(toggleDepth + 1)
      const offsetInParagraph = $from.pos - $from.start(toggleDepth + 1)
      const afterContent = paragraphNode.cut(offsetInParagraph).content.toJSON()

      const newAttrs = { isOpen: true }
      if (toggleNode.attrs.isTodo) {
        newAttrs.isTodo = true
        newAttrs.todoChecked = false
      }

      const { tr } = state
      tr.delete($from.pos, paragraphEnd)
      const newInsertPos = afterTogglePos - (paragraphEnd - $from.pos)
      tr.insert(
        newInsertPos,
        state.schema.nodeFromJSON({
          type: 'toggle',
          attrs: newAttrs,
          content: [{ type: 'paragraph', content: afterContent || [] }]
        })
      )
      tr.setSelection(TextSelection.near(tr.doc.resolve(newInsertPos + 2)))
      editor.view.dispatch(tr)
      return true
    }

    return {
      'Mod-Shift-t': () => this.editor.commands.setToggle(),

      // 엔터: 커서 위치에서 토글 분리
      'Enter': ({ editor }) => {
        const { state } = editor
        const { selection } = state

        // 토글 화살표/체크박스 선택 상태에서는 아무 동작 안 함
        if (selection instanceof NodeSelection || selection instanceof CheckboxSelection) return true

        const { $from } = selection
        const toggleDepth = findToggleDepth($from)
        if (toggleDepth === -1) return false

        const togglePos = $from.before(toggleDepth)
        const toggleNode = state.doc.nodeAt(togglePos)
        const afterTogglePos = togglePos + toggleNode.nodeSize
        const paragraphEnd = $from.end(toggleDepth + 1)

        if ($from.pos >= paragraphEnd)
          return handleEnterAtEnd(editor, $from, toggleDepth, toggleNode, togglePos, afterTogglePos)
        return handleEnterAtMiddle(editor, $from, toggleDepth, afterTogglePos, paragraphEnd, toggleNode)
      },

      // Shift+엔터: 블록 내부에서 줄바꿈 (soft break)
      'Shift-Enter': ({ editor }) => {
        return editor.commands.setHardBreak()
      },

      // 왼쪽 화살표: paragraph 시작 → CheckboxSelection → NodeSelection
      'ArrowLeft': ({ editor }) => {
        const { state } = editor
        const { selection } = state

        // CheckboxSelection → 토글 화살표 선택 (NodeSelection)
        if (selection instanceof CheckboxSelection) {
          const { tr } = state
          tr.setSelection(NodeSelection.create(state.doc, selection.togglePos))
          editor.view.dispatch(tr)
          return true
        }

        const { $from, empty } = selection
        if (!empty) return false

        const toggleDepth = findToggleDepth($from)
        if (toggleDepth === -1) return false

        const togglePos = $from.before(toggleDepth)
        const toggleNode = state.doc.nodeAt(togglePos)
        const paragraphStart = $from.start(toggleDepth + 1)

        if ($from.pos === paragraphStart) {
          // 투두 토글이면 CheckboxSelection
          if (toggleNode && toggleNode.attrs.isTodo) {
            const { tr } = state
            tr.setSelection(new CheckboxSelection(state.doc.resolve(togglePos + 2), togglePos))
            editor.view.dispatch(tr)
            return true
          }
          // 일반 토글이면 NodeSelection
          const { tr } = state
          tr.setSelection(NodeSelection.create(state.doc, togglePos))
          editor.view.dispatch(tr)
          return true
        }

        return false
      },

      // 오른쪽 화살표: CheckboxSelection/NodeSelection → paragraph 시작
      'ArrowRight': ({ editor }) => {
        const { state } = editor
        const { selection } = state

        // CheckboxSelection → paragraph 시작으로 복귀
        if (selection instanceof CheckboxSelection) {
          const { tr } = state
          tr.setSelection(TextSelection.create(state.doc, selection.togglePos + 2))
          editor.view.dispatch(tr)
          return true
        }

        // NodeSelection → 내부 paragraph 시작
        if (!(selection instanceof NodeSelection)) return false
        if (selection.node.type.name !== 'toggle') return false

        const insidePos = selection.from + 2
        const { tr } = state
        tr.setSelection(TextSelection.create(state.doc, insidePos))
        editor.view.dispatch(tr)
        return true
      },

      // 위 화살표: CheckboxSelection → 이전 todo 체크박스, NodeSelection → 토글 닫기
      'ArrowUp': ({ editor }) => {
        const { state } = editor
        const { selection } = state

        // CheckboxSelection → 이전 보이는 블록으로 이동
        if (selection instanceof CheckboxSelection) {
          const positions = collectVisiblePositions(state.doc)
          const currentIdx = positions.indexOf(selection.togglePos)
          if (currentIdx > 0) {
            const prevPos = positions[currentIdx - 1]
            const prevNode = state.doc.nodeAt(prevPos)
            if (prevNode && prevNode.type.name === 'toggle' && prevNode.attrs.isTodo) {
              const { tr } = state
              tr.setSelection(new CheckboxSelection(state.doc.resolve(prevPos + 2), prevPos))
              editor.view.dispatch(tr)
              return true
            }
            const { tr } = state
            const targetPos = prevPos + (prevNode.type.name === 'toggle' ? 2 : 1)
            tr.setSelection(TextSelection.near(state.doc.resolve(targetPos), 1))
            editor.view.dispatch(tr)
            return true
          }
          return false
        }

        if (!(selection instanceof NodeSelection)) return false
        if (selection.node.type.name !== 'toggle') return false

        // 이전 보이는 블록의 토글 화살표로 이동
        const positions = collectVisiblePositions(state.doc)
        const currentIdx = positions.indexOf(selection.from)
        if (currentIdx > 0) {
          const prevPos = positions[currentIdx - 1]
          const prevNode = state.doc.nodeAt(prevPos)
          if (prevNode && prevNode.type.name === 'toggle') {
            const { tr } = state
            tr.setSelection(NodeSelection.create(state.doc, prevPos))
            editor.view.dispatch(tr)
            return true
          }
          // 토글이 아닌 블록이면 텍스트 커서
          const { tr } = state
          tr.setSelection(TextSelection.near(state.doc.resolve(prevPos + 1), 1))
          editor.view.dispatch(tr)
          return true
        }
        return false
      },

      // 아래 화살표: CheckboxSelection/NodeSelection → 다음 보이는 블록
      'ArrowDown': ({ editor }) => {
        const { state } = editor
        const { selection } = state

        // CheckboxSelection → 다음 보이는 블록으로 이동
        if (selection instanceof CheckboxSelection) {
          const positions = collectVisiblePositions(state.doc)
          const currentIdx = positions.indexOf(selection.togglePos)
          if (currentIdx !== -1 && currentIdx < positions.length - 1) {
            const nextPos = positions[currentIdx + 1]
            const nextNode = state.doc.nodeAt(nextPos)
            if (nextNode && nextNode.type.name === 'toggle' && nextNode.attrs.isTodo) {
              const { tr } = state
              tr.setSelection(new CheckboxSelection(state.doc.resolve(nextPos + 2), nextPos))
              editor.view.dispatch(tr)
              return true
            }
            const { tr } = state
            const targetPos = nextPos + (nextNode.type.name === 'toggle' ? 2 : 1)
            tr.setSelection(TextSelection.near(state.doc.resolve(targetPos), 1))
            editor.view.dispatch(tr)
            return true
          }
          return false
        }

        if (!(selection instanceof NodeSelection)) return false
        if (selection.node.type.name !== 'toggle') return false

        // 다음 보이는 블록의 토글 화살표로 이동
        const positions = collectVisiblePositions(state.doc)
        const currentIdx = positions.indexOf(selection.from)
        if (currentIdx !== -1 && currentIdx < positions.length - 1) {
          const nextPos = positions[currentIdx + 1]
          const nextNode = state.doc.nodeAt(nextPos)
          if (nextNode && nextNode.type.name === 'toggle') {
            const { tr } = state
            tr.setSelection(NodeSelection.create(state.doc, nextPos))
            editor.view.dispatch(tr)
            return true
          }
          // 토글이 아닌 블록이면 텍스트 커서
          const { tr } = state
          tr.setSelection(TextSelection.near(state.doc.resolve(nextPos + 1), 1))
          editor.view.dispatch(tr)
          return true
        }
        return false
      },

      // Tab: 위 토글의 하위로 들여쓰기
      'Tab': ({ editor }) => {
        const { state } = editor
        const { $from } = state.selection

        const toggleDepth = findToggleDepth($from)
        if (toggleDepth === -1) return false

        const togglePos = $from.before(toggleDepth)
        const toggleNode = state.doc.nodeAt(togglePos)

        // 이전 형제 노드 찾기
        const $togglePos = state.doc.resolve(togglePos)
        const indexInParent = $togglePos.index($togglePos.depth)

        if (indexInParent === 0) {
          // 첫번째 자식이면 들여쓰기 불가
          return true
        }

        // 이전 형제 위치 계산
        const prevSiblingPos = $togglePos.posAtIndex(indexInParent - 1, $togglePos.depth)
        const prevSibling = state.doc.nodeAt(prevSiblingPos)

        if (!prevSibling || prevSibling.type.name !== 'toggle') {
          // 이전 형제가 토글이 아니면 들여쓰기 불가
          return true
        }

        // 이전 토글을 열고, 현재 토글을 이전 토글 끝에 삽입 후 원래 위치에서 삭제
        const tr = state.tr

        // 이전 토글이 닫혀있으면 열기
        if (!prevSibling.attrs.isOpen) {
          tr.setNodeMarkup(prevSiblingPos, null, { ...prevSibling.attrs, isOpen: true })
        }

        // 먼저 이전 토글의 끝에 삽입
        const insertPos = prevSiblingPos + prevSibling.nodeSize - 1
        tr.insert(insertPos, toggleNode)

        // 삽입 후 매핑된 위치에서 원래 토글 삭제
        const mappedTogglePos = tr.mapping.map(togglePos)
        tr.delete(mappedTogglePos, mappedTogglePos + toggleNode.nodeSize)

        editor.view.dispatch(tr)

        // 새 위치로 포커스
        const newCursorPos = tr.mapping.map(insertPos + 2)
        editor.commands.focus(newCursorPos)

        return true
      },

      // Backspace: 토글 첫 위치에서 토글 해제 방지, 단 빈 토글이면 삭제
      'Backspace': ({ editor }) => {
        const { state } = editor
        const { $from, empty } = state.selection

        if (!empty) return false

        const toggleDepth = findToggleDepth($from)
        if (toggleDepth === -1) return false

        const togglePos = $from.before(toggleDepth)
        const toggleNode = state.doc.nodeAt(togglePos)
        if (!toggleNode) return false

        // 커서가 블록 시작 위치에 있는지 확인
        const blockStart = $from.start(toggleDepth + 1)
        if ($from.pos !== blockStart) return false

        // 토글의 첫 번째 자식(index 0)인 경우에만 토글 해제 방지
        const indexInToggle = $from.index(toggleDepth)
        if (indexInToggle > 0) return false // 두 번째 이후 자식은 기본 동작 허용

        if ($from.pos === blockStart) {
          // 투두 토글이면 먼저 투두 해제
          if (toggleNode.attrs.isTodo) {
            const { tr } = state
            tr.setNodeMarkup(togglePos, null, { ...toggleNode.attrs, isTodo: false, todoChecked: false })
            editor.view.dispatch(tr)
            return true
          }

          // 첫 번째 paragraph이 비어있고 하위 토글이 없으면 → 토글 블록 삭제
          const firstChild = toggleNode.firstChild
          const isEmpty = firstChild && firstChild.content.size === 0 && !hasChildToggles(toggleNode)

          if (isEmpty) {
            // 이전 블록이 없으면 삭제 방지 (문서 첫 블록)
            if (togglePos === 0) return true

            const { tr } = state
            tr.delete(togglePos, togglePos + toggleNode.nodeSize)
            // 커서를 이전 블록 끝으로 이동
            if (togglePos > 0) {
              tr.setSelection(TextSelection.near(tr.doc.resolve(togglePos), -1))
            }
            editor.view.dispatch(tr)
            return true
          }

          // 내용이 있으면 토글 해제 방지
          return true
        }

        return false
      },

      // Shift+Tab: 토글 밖으로 내어쓰기
      'Shift-Tab': ({ editor }) => {
        const { state } = editor
        const { $from } = state.selection

        const toggleDepth = findToggleDepth($from)
        if (toggleDepth === -1) return false

        const togglePos = $from.before(toggleDepth)
        const toggleNode = state.doc.nodeAt(togglePos)

        // 부모 토글 찾기
        let parentToggleDepth = -1
        for (let d = toggleDepth - 1; d > 0; d--) {
          const node = $from.node(d)
          if (node.type.name === 'toggle') {
            parentToggleDepth = d
            break
          }
        }

        if (parentToggleDepth === -1) {
          // 부모 토글이 없으면 내어쓰기 불가 (이미 최상위)
          return true
        }

        // 부모 토글 다음 위치에 현재 토글 이동
        const parentTogglePos = $from.before(parentToggleDepth)
        const parentToggleNode = state.doc.nodeAt(parentTogglePos)
        const afterParentPos = parentTogglePos + parentToggleNode.nodeSize

        const tr = state.tr

        // 현재 토글 삭제
        tr.delete(togglePos, togglePos + toggleNode.nodeSize)

        // 부모 토글 다음에 삽입 (삭제로 인한 위치 조정)
        const adjustedInsertPos = afterParentPos - toggleNode.nodeSize
        tr.insert(adjustedInsertPos, toggleNode)

        editor.view.dispatch(tr)

        // 새 위치로 포커스
        editor.commands.focus(adjustedInsertPos + 2)

        return true
      },
    }
  },

  addInputRules() {
    return [
      // "[] " 입력 시 투두 토글로 변환
      new InputRule({
        find: /^\[\]\s$/,
        handler: ({ state, range }) => {
          const { tr, doc } = state
          const $from = doc.resolve(range.from)

          let toggleDepth = -1
          for (let d = $from.depth; d > 0; d--) {
            if ($from.node(d).type.name === 'toggle') {
              toggleDepth = d
              break
            }
          }
          if (toggleDepth === -1) return null

          const togglePos = $from.before(toggleDepth)
          const toggleNode = doc.nodeAt(togglePos)
          if (!toggleNode || toggleNode.attrs.isTodo) return null

          // "[] " 텍스트 삭제
          tr.delete(range.from, range.to)
          // 토글을 투두로 변환
          tr.setNodeMarkup(togglePos, null, { ...toggleNode.attrs, isTodo: true, todoChecked: false })
        },
      }),
      // "> " 입력 시 토글 블록으로 변환
      new InputRule({
        find: /^>\s$/,
        handler: ({ state, range, chain }) => {
          const { tr, doc } = state
          const $from = doc.resolve(range.from)

          // 현재 블록(paragraph)의 시작과 끝 위치
          const blockStart = $from.start()
          const blockEnd = $from.end()

          // "> " 이후의 기존 내용을 보존
          const remainingContent = doc.slice(range.to, blockEnd).content

          // 기존 내용이 있으면 포함하여 paragraph 생성, 없으면 빈 paragraph
          const innerParagraph = remainingContent.size > 0
            ? state.schema.nodes.paragraph.create(null, remainingContent)
            : state.schema.nodes.paragraph.create()

          // 토글 노드 생성 (기존 내용 포함)
          const toggleNode = state.schema.nodes.toggle.create(
            { isOpen: true },
            innerParagraph
          )

          // 현재 블록을 토글로 대체
          tr.replaceRangeWith(blockStart - 1, blockEnd + 1, toggleNode)

          // 토글 내부 paragraph로 커서 이동
          tr.setSelection(state.selection.constructor.near(tr.doc.resolve(blockStart + 1)))

          return tr
        },
      }),
    ]
  },
})
